cart/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

macromag/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^', include('landing.urls', namespace='landing'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),

    # url(r'^set_product/$', views.set_product),
    url(r'^prices_update/$', views.update_prices),
    url(r'^for_yandex/$', views.get_products_yml),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<id>\d+)/$', views.ProductDetail, name='ProductDetail'),
]

store/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлено")
    isPublish = models.BooleanField(default=False, verbose_name="Опубликован?")

    class Meta:
        abstract = True


class Formula(Base):
    text = models.CharField(max_length=200, verbose_name="Текст формулы",
                            help_text="Вместо переменной цены МВидео впиши ## (две решетки), например, (## - 1000) * 0.95")
    durationFrom = models.PositiveIntegerField(verbose_name="Минимальная цена",
                                               help_text="Ценовой минимум, при котором будет действовать формула")
    durationTo = models.PositiveIntegerField(verbose_name="Максимальная цена",
                                             help_text="Ценовой максимум, при котором будет действовать формула")

    class Meta:
        verbose_name = 'Формула'
        verbose_name_plural = 'Формулы'

    def __unicode__(self):
        return str(self.durationFrom) + " - " + str(self.durationTo) + " | " + self.text


# Модель категории
class Category(Base):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, verbose_name="Родитель", related_name="children")
    image = models.ImageField(upload_to='media/categories/%Y/%m/%d/', blank=True, verbose_name="Изображение категории")
    formules = models.ManyToManyField(Formula, verbose_name="Формулы", related_name="categories")
    delivery_cost = models.PositiveIntegerField(verbose_name="Стоимость доставки")

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(Base):

    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    mCode = models.CharField(max_length=8, verbose_name="Артикул МВидео")
    mUrl = models.URLField(verbose_name="Ссылка на сайт МВидео")
    typePrefix = models.CharField(max_length=200, db_index=True, verbose_name="Тип товара", null=True)
    vendor = models.CharField(max_length=200, db_index=True, verbose_name="Производитель", null=True)
    model = models.CharField(max_length=200, db_index=True, verbose_name="Модель", null=True)
    image = models.ImageField(upload_to='media/products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание", null=True)
    price = models.PositiveIntegerField(verbose_name="Цена", null=True)
    mPrice = models.PositiveIntegerField(verbose_name="Цена в МВидео", null=True)
    inStock = models.BooleanField(default=False, verbose_name="В наличии?")

    class Meta:
        ordering = ['typePrefix', 'vendor', 'model']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __unicode__(self):
        return self.typePrefix + ' ' + self.vendor + ' ' + self.model

    def get_absolute_url(self):
        return reverse('store:ProductDetail', args=[self.category.slug, self.id])


class Params(Base):
    name = models.CharField(max_length=200, verbose_name="Наименование")
    value = models.CharField(max_length=200, verbose_name="Значение")
    product = models.ForeignKey(Product, related_name="params", verbose_name="Товар")

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товара(ов)'

    def __unicode__(self):
        return self.name

store/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Product, Formula, Params
from cart.forms import CartAddProductForm
import requests
import json
import re
from lxml import etree
from datetime import datetime, timedelta
from django.core.files import File
# from tasks import update_prices


# Страница с товарами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.filter(isPublish=True)
    products = Product.objects.filter(isPublish=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'store/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


# Страница товара
def ProductDetail(request, category_slug, id):
    categories = Category.objects.filter(isPublish=True)
    product = get_object_or_404(Product, id=id, isPublish=True)
    cart_product_form = CartAddProductForm()
    return render_to_response('store/product/detail.html',
                             {'product': product,
                              'categories': categories,
                              'cart_product_form': cart_product_form})


def update_prices(request):
    if request.user.is_superuser:
        prod_all = Product.objects.all().order_by("updated_at")
        log = ""
        for p in prod_all:
            try:
                r_text = requests.get(p.mUrl).text
            except Exception:
                p.isPublish = False
                p.save()
                log += u"Product with ID " + str(p.id) + u" error request\n"
                continue
            if re.search(u'Товар распродан', r_text) or re.search(u'Cтраница не найдена\.', r_text):
                p.isPublish = False
                p.save()
                log += u"Product with ID " + str(p.id) + u" page not found or product sold out\n"
                continue
            try:
                id = re.search("'productId': '([0-9]+)'", r_text).group(1) if re.search("'productId': '([0-9]+)'", r_text) else re.search("c\-product\-code\">([0-9]+)", r_text).group(1)
                if p.mCode and id != p.mCode:
                    p.isPublish = False
                    p.save()
                    log += u"Product with ID " + str(p.id) + u" has mCode ("+p.mCode+u") but not equal with external ID ("+id+u")\n"
                    continue
                elif p.mCode != id:
                    p.mCode = id
                    p.save()
            except Exception:
                p.isPublish = False
                p.save()
                log += u"Product with ID " + str(p.id) + u" not found id\n"
                continue
            try:
                price = re.search("'productPriceLocal': '([0-9]+)\.", r_text).group(1) if re.search("'productPriceLocal': '([0-9]+)\.", r_text) else re.sub("[^0-9]+", "", re.search("c-pdp-price__current\">([^<]+)", r_text).group(1))
                p.mPrice = int(price)
            except Exception:
                p.isPublish = False
                p.save()
                log += u"Product with ID " + str(p.id) + u" not found price\n"
                continue
            try:
                formula = p.category.formules.filter(durationFrom__lte=p.mPrice, durationTo__gte=p.mPrice)[0]
                p.price = eval(formula.text.replace("##", str(
                    p.mPrice)))  # TODO добавить проверку на отсутствие символов отличных от цифр, +, -, *, /, (, ), ., #
            except Exception:
                p.price = p.mPrice
            p.isPublish = True
            p.inStock = True
            p.save()
    else:
        return HttpResponseRedirect('/')

    return render_to_response('store/report.html', {})


def escape_xml(str):
    return str.replace('&','&amp;').replace('"','&quot;').replace('\'','&apos;').replace('>','&gt;').replace('<','&lt;')


def get_products_yml(request):
    data = '<?xml version="1.0" encoding="utf-8"?>'
    xml = etree.Element("yml_catalog", date=datetime.now().strftime('%Y-%m-%d %H:%M'))
    shop = etree.SubElement(xml, "shop")
    etree.SubElement(shop, "name").text = "Macromag"
    etree.SubElement(shop, "company").text = u"ООО &quot;ЭЗРА&quot;"
    etree.SubElement(shop, "url").text = "http://macromag.ru"
    currencies = etree.SubElement(shop, "currencies")
    etree.SubElement(currencies, "currency", id="RUR", rate="1")
    categories = etree.SubElement(shop, "categories")
    for cat in Category.objects.filter(isPublish=True):
        if cat.parent and cat.parent.isPublish:
            etree.SubElement(categories, "category", id=str(cat.id), parentId=str(cat.parent.id)).text = escape_xml(cat.name)
        elif not cat.parent:
            etree.SubElement(categories, "category", id=str(cat.id)).text = escape_xml(cat.name)
    delivery_options = etree.SubElement(shop, "delivery-options")
    etree.SubElement(delivery_options, "option", cost="2000", days="1-3")
    offers = etree.SubElement(shop, "offers")
    for product in Product.objects.filter(isPublish=True, category__isPublish=True):
        if (product.category.parent and product.category.parent.isPublish) or not product.category.parent:
            offer = etree.SubElement(offers, "offer",
                                     id=str(product.id),
                                     type="vendor.model",
                                     available="true" if product.inStock else "false")
            etree.SubElement(offer, "url").text = "http://macromag.ru" + product.get_absolute_url()
            etree.SubElement(offer, "price").text = str(product.price)
            etree.SubElement(offer, "currencyId").text = "RUR"
            etree.SubElement(offer, "categoryId").text = str(product.category.id)
            etree.SubElement(offer, "picture").text = "http://macromag.ru" + product.image.url
            #etree.SubElement(offer, "pickup").text = "false"
            etree.SubElement(offer, "delivery").text = "true"
            do = etree.SubElement(offer, "delivery-options")
            etree.SubElement(do, 'option', cost=str(product.category.delivery_cost), days="1-3")
            etree.SubElement(offer, "typePrefix").text = escape_xml(product.typePrefix)
            etree.SubElement(offer, "vendor").text = escape_xml(product.vendor)
            etree.SubElement(offer, "model").text = escape_xml(product.model)
            etree.SubElement(offer, "manufacturer_warranty").text = "true"
            if product.params.count > 0:
                for param in product.params.all():
                    etree.SubElement(offer, "param", name=param.name).text = escape_xml(param.value)

    return HttpResponse(data + etree.tostring(xml), content_type="application/xml")

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock %}</title>
    <!-- Styles -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

    <link href="{% static "css/animate.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>
<body>
<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header" style="padding:0; text-align:center; ">
                    <div class="profile-element">
                        <a href="/" style="font-size:1.6em;"><img style=" background-color: white; width:77%" src="{% static 'img/logo.png' %}"/></a><br/>
                        <a href="tel:+79687078787"><big><i class="fa fa-phone"></i> +7(968)707-87-87</big></a>
                    </div>
                    <div class="logo-element" style="padding: 0 0 6px;">
                        <a href="/" style="font-size:1.6em;"><img style="background-color: white; width:77%" src="{% static 'img/logo_small.png' %}"/></a>
                    </div>
                </li>
                {% block sidenav %}{% endblock %}
            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg" style="overflow:hidden">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i>
                    </a>
                    <form role="search" class="navbar-form-custom" action="search_results.html">
                        <div class="form-group">
                            <input type="text" placeholder="Поиск товара..." class="form-control"
                                   name="top-search" id="top-search">
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                <a href="{% url 'cart:CartDetail' %}" class="m-r-sm" style="color:#1ab394; padding: 12px 8px"><big>
                                    <i class="fa fa-shopping-cart fa-lg"></i> {{ total_items }} тов. {{ cart.get_total_price }} руб.
                                </big></a>
                            {% else %}
                                <big><i class="m-r-sm fa fa-shopping-cart fa-lg" style="padding: 12px 8px"></i></big>
                            {% endif %}
                        {% endwith %}
                    </li>
                </ul>

            </nav>
        </div>
        <div class="row wrapper border-bottom white-bg page-heading" style="padding: 0 8px 8px">
            <div class="col-lg-10">
                <h2>{% block title %}{% endblock %}</h2>
                <ol class="breadcrumb" style="margin-bottom:8px">
                    {% block breadcrumb %}{% endblock %}
                </ol>
            </div>
            <div class="col-lg-2"></div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            {% block content %}{% endblock %}
        </div>
        <div class="footer">
            <div class="pull-right">
                Based on <strong>Inspinia</strong>
            </div>
            <div>
                <strong>Все права защищены</strong> MacroMAG &copy; 2017
            </div>
        </div>

    </div>
</div>

<!-- Mainly scripts -->
<script src="{% static "js/jquery-3.1.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "js/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static "js/inspinia.js" %}"></script>
<script src="{% static "js/plugins/pace/pace.min.js" %}"></script>
{% block js %}{% endblock %}
</body>
</html>

store/templates/store/base_new.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <title>{% block title %}{% endblock %}</title>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static "css/style_new.css" %}">
</head>

<body>
<body cz-shortcut-listen="true">
<header>
    <nav class="top-nav red lighten-1">
        <div class="container">
            <div class="nav-wrapper">
                <h5 style="margin:0;line-height:80px">Каталог товаров</h5>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url "cart:CartDetail" %}">
                                {{ total_items }} тов. {{ cart.get_total_price }} руб.
                            </a>
                        {% else %}
                            <i class="material-icons medium">shopping_cart</i>
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container"><a href="#" data-activates="nav-mobile"
                              class="button-collapse top-nav full hide-on-large-only"><i class="material-icons">menu</i></a>
    </div>
    <ul id="nav-mobile" class="side-nav fixed" style="transform: translateX(0px);">
        <li class="logo"><a id="logo-container" href="/"
                            class="brand-logo waves-effect waves-teal red-text text-lighten-1"><big>DiEl store</big></a>
        </li>
        <li class="search">
            <div class="search-wrapper card">
                <input id="search"><i class="material-icons">search</i>
                <div class="search-results"></div>
            </div>
        </li>
        <li class="bold{% if not category %} active{% endif %}">
            <a class="waves-effect waves-teal" href="{% url "store:ProductList" %}">Все</a>
        </li>
        {% for cat in categories %}
            {% if not cat.parent and cat.isPublish %}
                <li class="{% if category and category.slug == cat.slug %}active {% endif %}bold">
                    <a class="waves-effect waves-teal" href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold"><a class="collapsible-header  waves-effect waves-teal">CSS</a>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="color.html">Цвет</a></li>
                        </ul>
                    </div>
                </li>
                <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Components</a>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="badges.html">Badges</a></li>
                        </ul>
                    </div>
                </li>
                <li class="bold"><a class="collapsible-header  waves-effect waves-teal">JavaScript</a>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="carousel.html">Carousel</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="bold active"><a href="showcase.html" class="waves-effect waves-teal">Примеры сайтов</a></li>
    </ul>
</header>
<main>
    <div class="container section">
        <div class="col s12">
            <a href="#!" class="breadcrumb red-text text-lighten-1">First</a>
            <a href="#!" class="breadcrumb red-text text-lighten-1">Second</a>
            <a href="#!" class="breadcrumb red-text text-lighten-1">Third</a>
        </div>

    </div>
    <section id="content" class="container">
        {% block content %}{% endblock %}
    </section>
</main>
<footer class="page-footer red lighten-1">
    <div class="container">
        <div class="row">
            <div class="col l4 m6 s12">
                <h5 class="white-text">Контакты</h5>
                <p class="white-text">Наименование магазина:<br/><b>DieL store</b></p>
                <p class="white-text"><b><i class="material-icons tiny" style="vertical-align:sub">location_on</i> г.
                    Москва, ул. Верхняя Красносельская, д. 16Б, стр. 2</b></p>
                <p class="white-text"><b><i class="material-icons tiny" style="vertical-align:sub">call</i>
                    +7(499)130-30-65</b></p>
                <p class="white-text"><b><i class="material-icons tiny" style="vertical-align:sub">mail_outline</i>
                    dielstore@yandex.ru</b></p>
                <p class="white-text"><b><i class="material-icons tiny" style="vertical-align:sub">access_time</i> с
                    10:00 до 20:00 (без выходных)</b></p>
                <p class="white-text">Наименование юр лица:<br/><b>ООО "КОМСМАРТ"</b></p>
                <p class="white-text"><b><i class="material-icons tiny" style="vertical-align:sub">mail</i> 125414, г.
                    Москва, ул. Петрозаводская, д. 8</b></p>
                <p class="white-text">ОГРН:<br/><b>1157746947808</b></p>
                <h5 class="white-text">Оплата</h5>
                <p class="white-text">Оплатить заказ можно <b>только за наличный расчет</b> курьеру при получении
                    товара.</p>
            </div>
            <div class="col l4 m6 s12">
                <h5 class="white-text">Доставка по Москве и МО</h5>
                <p class="white-text">Доставка осуществляется <b>в течение 3-х дней</b> с момента оформления заказа.
                    Доставка возможна по Москве и ближайшему Подмосковью (до <b>30 км от МКАД</b>).
                    Стоимость доставки <b>от 300 руб. до 2000 руб.</b>, в зависимости от веса и габаритов товара. Выезд
                    за МКАД оплачивается отдельно: <b>25 руб./км</b>.
                    Итоговую стоимость доставки сообщает менеджер при подтверждении заказа. Курьер с Вами свяжется за
                    час до осуществления доставки.</p>
                <h5 class="white-text">Самовывоза нет!</h5>
                <h5 class="white-text">Правила обмена и возврата</h5>
                <p class="white-text">В течение 14 денй с момента покупки Вы можете вернуть товар если он имеет явный
                    заводской брак! Важно, что были соблюдены следующие требования:</p>
                <ul class="white-text" style="text-indent:16px">
                    <li> - Сохранена оригинальная упаковка (полностью)</li>
                    <li> - Сохранены аксессуары, сопроводительная документация и ПО, расходные материалы, ярлыки и
                        компоненты товара
                    </li>
                    <li> - Не производилась установка товара</li>
                    <li> - Сохранен кассовый чек</li>
                    <li> - Товар не имеет следов использования</li>
                    <li> - Сохранены заводские пломбы</li>
                </ul>
            </div>

            <div class="col l4 m6 s12">
                <h5 class="white-text">Гарантия</h5>
                <b class="white-text">Вся техника, приобретаемая у нас, имеет официальную гарантию от производителя и
                    сертифицирована!</b>

                <h5 class="white-text">Не подлежит возврату</h5>
                <u class="white-text">Cогласно «Закону о защите прав потребителей»:</u>
                <ul class="white-text">
                    <li>4. Текстильные товары (хлопчатобумажные, льняные, шелковые, шерстяные и синтетические ткани,
                        товары из нетканых материалов типа тканей - ленты, тесьма, кружево и другие); <b>кабельная
                            продукция (провода, шнуры, кабели);</b> строительные и отделочные материалы (линолеум,
                        пленка, ковровые покрытия и другие) и <b>другие товары, отпускаемые на метраж</b> <i>(п. 4 в
                            ред. Постановления Правительства РФ от 20.10.1998 N 1222)</i></li>
                    <li>11. Технически сложные товары бытового назначения, на которые установлены гарантийные сроки
                        (станки металлорежущие и деревообрабатывающие бытовые; <b>электробытовые машины и приборы;
                            бытовая радиоэлектронная аппаратура;</b> бытовая вычислительная и множительная техника; <b>фото-
                            и киноаппаратура; телефонные аппараты</b> и факсимильная аппаратура; <b>электромузыкальные
                            инструменты;</b> игрушки электронные, <b>бытовое газовое оборудование и устройства</b>) <i>(в
                            ред. Постановлений Правительства РФ от 20.10.1998 N 1222, от 06.02.2002 N 81)</i></li>
                </ul>
            </div>

        </div>
    </div>
    <div class="footer-copyright red darken-1">
        <div class="container white-text">© 2016-2017 DiEl store. Все права защищены.</div>
    </div>
</footer>
</body>
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.button-collapse').sideNav({'edge': 'left'});
        function is_touch_device() {
            try {
                document.createEvent("TouchEvent");
                return true;
            } catch (e) {
                return false;
            }
        }

        if (is_touch_device()) {
            $('#nav-mobile').css({overflow: 'auto'});
        }
    })
</script>
{% block js %}{% endblock %}
</body>
</html>

store/templates/store/report.html
<!DOCTYPE html>
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
    <ul class="collection with-header">
        <li class="collection-header"><h4>Отчет об изменении цен</h4></li>
        <li class="collection-item">Затрачено времени<span class="badge">{{ time_delta }} сек</span></li>
        <li class="collection-item">Успешно обновлено продуктов<span class="badge">{{ good_count }}</span></li>
        <li class="collection-item">Количество ошибок<span class="badge">{{ bad_count }}</span></li>
    </ul>
    <h4>Продукты, обновление которых завершено не удачно</h4>
    <table class="striped">
        <thead>
            <tr>
                <th></th>
                <th>Артикул</th>
                <th>Наименование</th>
                <th>Проблема</th>
            </tr>
        </thead>

        <tbody>
            {% for item in bad_list %}
            <tr>
                <td><i class="material-icons">{{ item.type }}</i></td>
                <td>{{ p.id }}</td>
                <td><a href="{{ p.get_absolute_url }}">{{ p }}</a></td>
                <td>{{ p.text }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
</body>
</html>