cart/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

macromag/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^', include('landing.urls', namespace='landing'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^torg12/(?P<id>\d+)/$', views.get_torg12)
]

orders/models.py
# -*- coding: utf-8 -*-
from django.db import models
from store.models import Product


class Order(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(verbose_name='Адрес доставки', max_length=250, blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=20)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)
    comments = models.TextField(verbose_name="Комментарий", blank=True, default="")
    comments_in = models.TextField(verbose_name="Комментарий внутренний", blank=True, default="")

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.id)

    def get_delivery_cost(self):
        delivery_cost = 0
        quantity = -1
        for item in self.items.all():
            quantity += item.quantity
            if delivery_cost < item.product.category.delivery_cost:
                delivery_cost = item.product.category.delivery_cost
        if quantity > 0:
            delivery_cost += 100 * quantity
            #     12.06.2017 22:30, Эл сказал убрать ограничение в 2000 рублей
            # if delivery_cost > 2000:
            #     delivery_cost = 2000
        return delivery_cost

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all()) + self.get_delivery_cost()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'phone', 'address', 'comments']

orders/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from store.models import Category
# from .tasks import OrderCreated


def OrderCreate(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            # Асинхронная отправка сообщения
            # OrderCreated(order.id)
            return render(request, 'orders/order/created.html', {'cart': cart,  'form': form, 'order': order})

    form = OrderCreateForm()
    categories = Category.objects.filter(isPublish=True)
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form,
                                                        'categories': categories})


def get_torg12(request, id):
    order = Order.objects.get(id=id)
    return render(request, 'orders/order/torg12.html', {'order': order, 'delivery_num': order.items.count() + 1})

orders/templates/orders/order/create.html
{% extends "store/base.html" %}

{% load static %}

{% block head_title %}
  Оформление заказа
{% endblock %}
{% block title %}
  Оформление заказа
{% endblock %}

{% block sidenav %}
    {% for cat in categories %}
        {% if not cat.parent and cat.isPublish %}
            <li>
                <a href="{{ cat.get_absolute_url }}">
                    <img src="{% if cat.image %}{{ cat.image.url }}{% else %}{% static 'img/no-image.jpg' %}{% endif %}" style="width:20px; height:20px; opacity:0.8;-webkit-filter: grayscale(100%);-moz-filter: grayscale(100%);-ms-filter: grayscale(100%);-o-filter: grayscale(100%);filter: grayscale(100%);filter: gray; /* IE 6-9 */"/>
                    <span class="nav-label">&nbsp;{{ cat.name }}</span>
                    {% if cat.children.count %}<span class="fa arrow"></span>{% endif %}
                </a>
                {% if cat.children.count %}
                    <ul class="nav nav-second-level collapse {% if category.slug == cat.slug or category.parent.slug == cat.slug %} in {% endif %}">
                    {% for subcat in cat.children.all %}
                        <li {% if category.slug == subcat.slug %} class="active" {% endif %}>
                            <a href="{{ subcat.get_absolute_url }}">{{ subcat.name }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block breadcrumb %}
    <li>
        <a href="/">Главная</a>
    </li>
    <li>
        <a href="{% url 'store:ProductList' %}">Каталог товаров</a>
    </li>
    <li class="active">
        <a href="{% url 'orders:OrderCreate'%}">Оформление заказа</a>
    </li>
{% endblock %}

{% block content %}
  <div class="col-lg-6 col-md-12">
    <div class="ibox">
        <div class="ibox-title"><h5>Заполните форму</h5></div>
        <div class="ibox-content">
            <form id="order-form" class="order-form" action="." method="post">
                {% for field in form %}
                    <div class="form-group">
                        <label style="text-transform: uppercase">{{ field.label_tag }}</label><br/>
                        {{ field }}
                        <span class="text-danger">{{ field.error }}</span>
                    </div>
                {% endfor %}
              {% csrf_token %}

            </form>
        </div>
        <div class="ibox-footer"><button class="btn btn-primary" type="submit" form="order-form">Сделать заказ</button></div>
    </div>

  </div>

  <div class="col-lg-6 col-md-12">
    <div class="ibox">
        <div class="ibox-title"><h5>Ваш заказ</h5></div>
        <div class="ibox-content">
          <ol class="order-info">
              {% for item in cart  %}
                <li>
                  {{ item.product.typePrefix }} {{ item.product.vendor }} {{ item.product.model }} | Количество: {{ item.quantity }} | Цена: {{ item.total_price }}₽
                </li>

              {% endfor %}
                <li>Доставка | Цена: <span id="delivery-cost">{{ cart.get_delivery_cost }}</span> | <b><i>В стоимость доставки не входит километраж за пределами МКАД, МКАД оплачивается отдельно: 25 руб./км. Итоговую стоимость доставки сообщает менеджер при подтверждении заказа.</i></b></li>
            </ol>
        </div>
        <div class="ibox-footer">


            <h2 class="font-bold" style="margin:0">
                <small>Итого:</small> <span id="order-price">{{ cart.get_order_price }}</span>₽
            </h2>
        </div>
    </div>
  <div class="ibox">
    <div class="ibox-title">
        <h5>Нужна помощь?</h5>
    </div>
    <div class="ibox-content text-center">
        <h3><a href="tel:+79687078787" class="text-navy"><i class="fa fa-phone"></i> +7(968)707-87-87</a></h3>
        <span class="small">
            Если у Вас возникли вопросы, связанные с приобретением товара у нас на сайте, Вы можете позвонить нам с 10:00 до 20:00, ежедневно, без праздников и выходных.
        </span>


    </div>
    </div>
  </div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$(document).ready(function(){
    var delivery = $('.order-info li:last');
    var delivery_cost = parseInt(delivery.find('#delivery-cost').text());
    var order_price = $('#order-price');
    $('#id_pickup').change(function(e){
        if ($(e.target).prop('checked')){
            order_price.text(parseInt(order_price.text()) - delivery_cost);
            delivery.hide('fast');
        } else {
            order_price.text(parseInt(order_price.text()) + delivery_cost);
            delivery.show('fast');
        }
    });
});
</script>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "store/base.html" %}

{% block title %}
  Спасибо за заказ
{% endblock %}

{% block content %}
  <h1>Спасибо за заказ</h1>
  <p>Идентификатор вашего заказа: <b>{{ order.id }}</b></p>
    <p>В скором времени с Вами свяжется представитель магазина.</p>
{% endblock %}

orders/templates/orders/order/torg12.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Заказ №{{ order.id }}</title>
    <style type="text/css">
        *{
            font-family: Arial, sans-serif;
        }
        body{
            width:100%;
            padding:0;
            margin:0;
        }
        td{
            vertical-align: top;
        }
        .w100{ width:100%;}
        .fwb{font-weight: bold;}
        .tcenter{text-align: center;}
        .tright{text-align: right;}
        .br{border-right: 1px solid black;}
        .bb{border-bottom: 1px solid black;}
        .btb{border-top: 2px solid black;}
        .blb{border-left: 2px solid black;}
        .brb{border-right: 2px solid black;}
        .bbb{border-bottom: 2px solid black;}
        .order-items{ margin-bottom: 8px;}
    </style>
</head>
<body>
<h1 class="tcenter">MACROMAG</h1>
<div class="w100 bbb fwb tcenter"><big>Заказ № {{ order.id }} от {{ order.created }}</big></div>
<br/>
<table cellspacing="0" border="0">
    <tr>
        <td>Продавец:</td>
        <td>Интернет-магазин MACROMAG, г. Москва, Профсоюзная, д. 16/10</td>
    </tr>
    <tr>
        <td>Заказчик:</td>
        <td>{{ order.name }}, {{ order.email }}, {{ order.phone }}, {{ order.address }}</td>
    </tr>
</table>
<br/>
<table width="100%" cellspacing="0" border="1" class="order-items">
    <thead>
        <tr>
            <th>№</th>
            <th>Товары (работы, услуги)</th>
            <th colspan="2">Количество</th>
            <th>Цена</th>
            <th>Сумма</th>
        </tr>
    </thead>
    <tbody>
    {% for item in order.items.all %}
        <tr>
            <td class="tcenter">{{ forloop.counter }}</td>
            <td>{{ item.product }}</td>
            <td class="tcenter">{{ item.quantity }}</td>
            <td class="tcenter">шт</td>
            <td class="tright">{{ item.price }}</td>
            <td class="tright">{{ item.get_cost }}</td>
        </tr>
        {% endfor %}
        {% if not order.pickup %}
        <tr>
            <td class="tcenter">{{ delivery_num }}</td>
            <td> Доставка заказа </td>
            <td class="tcenter">1</td>
            <td class="tcenter">ед</td>
            <td class="tright"> {{ order.get_delivery_cost }},00</td>
            <td class="tright"> {{ order.get_delivery_cost }},00</td>
        </tr>
    {% endif %}
    </tbody>
</table>
<div class="tright fwb"><big>Итого: {{ order.get_total_cost }}</big></div>
<br/>
<br/>
<p class="fwb">Менеджер _______________________________________________________________________</p>

<p>Телефон: +7(968)707-87-87<br/>
Сайт: macromag.ru<br/>
E-mail: info@macromag.ru</p>
<br/>
<br/>
<p class="fwb">Обмен/возврат товара может быть произведён в течении 14 календарных дней после покупки,
    при условии, что товар не был в эксплуатации, сохранён его товарный вид, потребительские свойства, комплектация,
    пломбы и фабричная упаковка (за исключением гарантийного случая).<br/>
    Для обмена/возврата товара необходимо предъявить чек и данную накладную.<br/>
    Исправность товара и внешний вид мною проверены, претензий не имею.<br/>
    Подтверждаю получение полной информации о товаре, его функциях, комплектации, гарантии.</p>
<br/>
<p class="fwb">Подпись _______________</p>
</body>
</html>